### PR TITLE
Added profile norabalogh

### PR DESCRIPTION
**Pull request by noratenk**
Added a profile card norabalogh ;)

### CODE REVIEW

**Review by YASHMAROO — CHANGES_REQUESTED** [review]
Please append your profile at he end of the array and follow the guidelines strictly.

**Comment by noratenk** [comment]
> Please append your profile at the end of the array and follow the guidelines strictly.

Hi @YASHMAROO, I have made the changes. Thanks! :)

**Comment by noratenk** [comment]
> Please append your profile at the end of the array and follow the guidelines strictly.

Hi @YASHMAROO, I have made the changes. Thanks! :)

**Comment by noratenk** [comment]
Hi @YASHMAROO! I have made the changes. Could you please review my PR again? Thanks!

**Comment by Abha2001** [comment]
Thank you for your contribution!

**Pull request merged**
