### PR TITLE
2019

### LINKED ISSUE #70: Add statistics page alogwith statistics using Chart JS
Kindly discuss the stats that can be shown before starting to make it.

### PR DESCRIPTION
**Pull request by Abha2001**
issue #70. added stats.

### CODE REVIEW

**Review by arc9693 — CHANGES_REQUESTED** [review]
- [ ] Roll back the theme of everything else other than the "charts" on the stats page to what it was before
- [ ] Make the headings of all charts of identical font size
- [ ] Keep the charts sized identically

**Comment by Abha2001** [comment]
>     * [x]  Roll back the theme of everything else other than the "charts" on the stats page to what it was before
> 
>     * [x]  Make the headings of all charts of identical font size
> 
>     * [x]  Keep the charts sized identically

**Comment by Abha2001** [comment]
- [x]  Roll back the theme of everything else other than the "charts" on the stats page to what it was before
- [x]  Make the headings of all charts of identical font size
- [x]  Keep the charts sized identically

**Comment by arc9693** [comment]
@Abha2001  I am merging this PR. Good work.

**Pull request merged**
