### PR TITLE
added a repo card jenkins-centos-aws-linux-setup-script

### PR DESCRIPTION
**Pull request by parth93QA**

### CODE REVIEW

**Comment by YASHMAROO** [comment]
Thank You for making a repo card to this pr ....Kudos !!!!

**Review by YASHMAROO — CHANGES_REQUESTED** [review]
Please follow the structure strictly and add a space after "repo_link": as the other links that are added in the array..

**Comment by parth93QA** [comment]
changed can you merge

**Comment by YASHMAROO** [comment]
Thank you for adding a repo card and I have merged your pr .

**Pull request merged**
