### PR TITLE
Added User: "d-schaffer" to the other Users in data.json

### PR DESCRIPTION
**Pull request by d-schaffer**
Add me to Card

### CODE REVIEW

**Review by YASHMAROO — CHANGES_REQUESTED** [review]
It was mentioned that you need to append your profile at the end of the array . Please make the necessary changes and write a proper commit message and squash the commits into one.

**Comment by d-schaffer** [comment]
@YASHMAROO i hope it is okay now :)

**Review by d-schaffer — COMMENTED** [review]
i fixed it

**Review by d-schaffer — COMMENTED** [review]
hey, i fixed it, i took it to the end of the json

**Pull request merged**
