### PR TITLE
Profile Added

### PR DESCRIPTION
**Pull request by rishavjaiss**
Hey,

Please review this pr and merge. Thanks!

### CODE REVIEW

**Review by arc9693 — CHANGES_REQUESTED** [review]
Can you squash these two commits into one as is specified in contributing guidelines?

**Comment by rishavjaiss** [comment]
Actually by the time I made the pr, some other contributor did it and then it was a merge conflict shown. Now I don't know how to squash them. Can you help?

**Comment by Abha2001** [comment]
@rishavjaiss you may refer to [this](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) article to get an idea of how to squash commits.

**Comment by rishavjaiss** [comment]
@Abha2001 maintainers have the ability to squash & merge only. From my end I have to make a fresh pr again. You must get an  option to squash and merge, please try that.

**Comment by Abha2001** [comment]
It is also possible for the contributors to rebase and squash the commits and then send in a PR. SInce the contributing guidelines ask for such a case where there is only one commit, please try to do that!

**Pull request closed without merging**
