### PR TITLE
Added profile awaisrafiq410

### PR DESCRIPTION
**Pull request by awaisrafiq410**

### CODE REVIEW

**Comment by awaisrafiq410** [comment]
Parden for any wrong thing. I'm new

**Review by arc9693 — CHANGES_REQUESTED** [review]
Welcome to the community! :-)  
Would you just add append your profile to the end of the list?

**Comment by awaisrafiq410** [comment]
Profile moved to last

@arc9693  Close this if there no more changes need

**Review by arc9693 — COMMENTED** [review]
The json file syntax has been altered due to your changes. Kindly correct them. You can also close this and open another PR if you want.

**Review by arc9693 — APPROVED** [review]

**Pull request closed without merging**
